### PR TITLE
fix(github): handle Copilot actor without user profile fetch

### LINKED ISSUE #859: [Bug]: Failed to convert Copilot user's fields because of 404 issue
### Contact Details

_No response_

### What happened?

In the production logs, there are a lot of errors regarding to Copilot user. I don't know if how critical this error logs are. This issue should be investigated, its root cause and solution should be added to Comments section.

### Steps To Reproduce

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
2026-01-10T00:47:55.020Z ERROR 1 --- [Helios] [nats:4] .t.c.a.h.g.BaseGitServiceEntityConverter : Failed to convert createdAt field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:55.020Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:55.162Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (142ms, unknown-length body)
2026-01-10T00:47:55.162Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12452, used=48, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:55.163Z ERROR 1 --- [Helios] [nats:4] .t.c.a.h.g.BaseGitServiceEntityConverter : Failed to convert updatedAt field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:55.163Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:55.490Z DEBUG 1 --- [Helios] [default-scheduler-2] d.t.c.a.h.e.status.StatusCheckScheduler  : Starting scheduled status checks.
2026-01-10T00:47:55.501Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (338ms, unknown-length body)
2026-01-10T00:47:55.501Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12451, used=49, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:55.502Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user name field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:55.502Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:55.631Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (128ms, unknown-length body)
2026-01-10T00:47:55.631Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12450, used=50, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:55.631Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user company field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:55.631Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:55.691Z DEBUG 1 --- [Helios] [default-scheduler-2] d.t.c.a.h.e.status.StatusCheckScheduler  : Found 9 environments with status check type configured. 9 stable (checking 0 now), 0 recent
2026-01-10T00:47:55.691Z DEBUG 1 --- [Helios] [default-scheduler-2] d.t.c.a.h.e.status.StatusCheckScheduler  : Scheduled status checks completed in 0.0 seconds.
2026-01-10T00:47:55.791Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (159ms, unknown-length body)
2026-01-10T00:47:55.791Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12449, used=51, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:55.792Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user blog field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:55.792Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:55.965Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (172ms, unknown-length body)
2026-01-10T00:47:55.965Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12448, used=52, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:55.966Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user location field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:55.966Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:56.119Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (153ms, unknown-length body)
2026-01-10T00:47:56.120Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12447, used=53, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:56.120Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user email field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:56.120Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:56.257Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (137ms, unknown-length body)
2026-01-10T00:47:56.258Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12446, used=54, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:56.258Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user type field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:56.258Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:56.390Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (132ms, unknown-length body)
2026-01-10T00:47:56.390Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12445, used=55, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:56.391Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user followers field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T00:47:56.391Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : --> GET https://api.github.com/users/Copilot
2026-01-10T00:47:56.528Z  INFO 1 --- [Helios] [nats:4] okhttp3.OkHttpClient                     : <-- 404 https://api.github.com/users/Copilot (136ms, unknown-length body)
2026-01-10T00:47:56.528Z  INFO 1 --- [Helios] [nats:4] t.c.a.h.h.HttpClientRateLimitInterceptor : GitHub API Rate Limit: limit=12500, remaining=12444, used=56, resets at 10/01/2026 01:18:58 (UTC), 10/01/2026 02:18:58 (CET)
2026-01-10T00:47:56.529Z ERROR 1 --- [Helios] [nats:4] d.t.c.a.h.u.github.GitHubUserConverter   : Failed to convert user following field for source 198982749: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}


...


2026-01-10T06:01:47.072Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/add-research-opt-out-settings: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:47.974Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/add-storybook-footer-link: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:49.769Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/fix-03cdc29e-61a5-4be6-a175-bb03699811e5: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:50.610Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/fix-duplicate-key-issue: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:51.721Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/fix-fb524e00-c731-4e98-bcef-3ecd2c619fd6: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:52.598Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/fix-version-display-issue: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:53.439Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/remove-footer-variables-production: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:54.165Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/setup-development-environment: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
2026-01-10T06:01:55.081Z ERROR 1 --- [Helios] [default-scheduler-1] d.t.c.a.h.b.g.GitHubBranchSyncService    : Failed to link updatedBy user for pull request copilot/sub-pr-519: https://api.github.com/users/Copilot {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
```

### PR DESCRIPTION
**Pull request by mertilginoglu**
### Motivation
Production logs contain repeated errors when syncing GitHub actors with login `Copilot`.

The GitHub API returns `404 Not Found` for `GET /users/Copilot`, but Helios attempted to fetch multiple profile fields and user timestamps anyway. This caused noisy error logs and unnecessary API calls during branch/user sync.

Fixes #859.

### Description
- Added a Copilot-specific fallback path in `GitHubUserConverter`:
  - Detects `Copilot` login case-insensitively via `isCopilotActorLogin(...)`.
  - Builds/stores a minimal BOT user model without triggering profile field fetches that call `/users/Copilot`.
  - Emits a single warning log for this synthetic actor mapping.
- Updated `GitHubBranchSyncService` to set branch `updatedAt` from commit metadata (`commitDate`) instead of `updatedBy.getUpdatedAt()` to avoid profile fetches for Copilot actors.
- Added unit tests for Copilot login detection in `GitHubUserConverterTest`.

#### Prerequisites:
- Helios server environment configured locally
- Access to run Gradle tests
- Checking Grafana logs for staging.

#### Flow:
1. Check out branch `fix/copilot-actor-404`.
2. Run:
   ```bash
   cd server
   ./gradlew :application-server:test --tests de.tum.cit.aet.helios.user.github.GitHubUserConverterTest
   ```
3. Verify tests pass.
4. Optional integration verification:
   - Trigger GitHub sync on a repository with Copilot-authored branches/PRs.
   - Confirm no repeated `/users/Copilot` conversion errors are produced.

### Screenshots
No UI changes were made.

#### General
- [x] PR description explains the purpose and changes. [(f.e. following the 'Conventional Commits')](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Changes have been tested locally.

#### Server
- [x] Code is performant and follows best practices
- [x] I documented the Java code using JavaDoc style.

### CODE REVIEW

File: server/application-server/src/main/java/de/tum/cit/aet/helios/user/github/GitHubUserConverter.java [hunk 1]
```diff
@@ -48,67 +49,81 @@ public User convertToExpirationPicker() {
...
+    user.setUpdatedAt(now);
+    user.setLogin(source.getLogin());
+    user.setAvatarUrl(source.getAvatarUrl());
+    user.setDescription("Copilot bot actor from GitHub metadata.");
+    user.setName("GitHub Copilot");
+    user.setCompany(null);
+    user.setBlog(null);
+    user.setLocation(null);
+    user.setEmail(null);
+    user.setHtmlUrl("https://github.com/apps/copilot");
```
Comment (meryemefe) [inline server/application-server/src/main/java/de/tum/cit/aet/helios/user/github/GitHubUserConverter.java]: Hi Mert, I tested it in my local, it is working. My only comment is that, you don't need to set htmlUrl as hardcoded. I used debugger and saw that htmlUrl field doesn't cause any problem.

Image

**Comment by meryemefe** [comment]
Also, I realized something, I think you accidentally checked  " Screenshots have been attached." item and left "I documented the Java code using JavaDoc style." empty. Therefore in the Pull Request page, I saw only 4/5 items as completed for this PR.

**Review by meryemefe — APPROVED** [review]
